### ISSUE TITLE
OutOfMemoryError: CUDA out of memory, while running the sam3_video_predictor_example.ipynb notebook

### ISSUE THREAD

**Issue by lborreill** [facebookresearch/sam3#169]
Hello, first of all thank you for the incredible work on SAM3. I tried it on a few videos and it is detecting, tracking and segmenting everything amazingly so far.

While running the `sam3_video_predictor_example.ipynb` notebook on a video longer than `assets/videos/0001`, I encounter an `OutOfMemoryError` on my CUDA device.

The `predictor._ALL_INFERENCE_STATES` dictionary in the session I create seems to grow larger after each loop in the notebook’s `propagate_in_video()` function, where some variables are stored on the CUDA device. I slightly modified the code to load SAM3 with `async_loading_frames=True` and to start my session with `offload_video_to_cpu=True`, which reduced memory usage, but not enough for longer videos.

With SAM2, I was able to avoid OOM errors by following the recommendations here: [https://github.com/facebookresearch/sam2/issues/264](url), but they don’t seem to help with SAM3.

I haven’t found a solution yet but is there a way to significantly reduce memory usage without offloading everything to RAM?

Thank you in advance for any help you can provide.

**Comment by ibaiGorordo** [comment]
A lot of memory goes into inference_state["cached_frame_outputs"], if you don't need to access the same frame again, commeting this part reduces the memory significantly: https://github.com/facebookresearch/sam3/blob/84cc43bca4347b772f17d1078a1ddb4c054655c2/sam3/model/sam3_video_inference.py#L548

**Comment by ibrahere123** [comment]
Does this work?

**Comment by qpc001** [comment]
> Does this work?这个有用吗

a little bit. But not solve the problem.

**Comment by ibrahere123** [comment]
I found a way to run the sam3 on video using the image model.Lmk if u need the scripts :)

**Comment by lborreill** [comment]
> I found a way to run the sam3 on video using the image model.Lmk if u need the scripts :)

Does it help reducing the memory usage ?

**Comment by ibrahere123** [comment]
Yes it does i m running locally on my system 3050 6gb vram .

**Comment by lborreill** [comment]
> Yes it does i m running locally on my system 3050 6gb vram .

Then I would like see your scripts please.

**Comment by luh-j** [comment]
> > Yes it does i m running locally on my system 3050 6gb vram .
> 
> Then I would like see your scripts please.

Would love to see that as well! Thanks

**Comment by ibrahere123** [comment]
https://github.com/ibrahere123/Sam3-locall-inference/blob/master/sam3_inference_framewise.py

Take look at this ,and lmk if it works for you.Also if u can star i wont mind :)

**Comment by Ideenaster** [comment]
This aligns with my experiments, meaning that the current massive GPU memory consumption of sam3 mainly stems from the inference_state. However, running the image model frame by frame without a tracking mechanism is not beneficial for my task.

**Comment by lborreill** [comment]
I managed to offload a lot of memory to CPU RAM. To do so, I set those parameters when building the model:
```
predictor = build_sam3_video_predictor(
    gpus_to_use=gpus_to_use, 
    offload_video_to_cpu=True,
    offload_state_to_cpu=True,
    async_loading_frames=True,
    forward_backbone_per_frame_for_eval=True,
    trim_past_non_cond_mem_for_eval=True,
    offload_output_to_cpu_for_eval=True,
)
```
Some parameters are not arguments of `build_sam3_video_predictor` without modifying the code. You can download my modified files here:

sam3/sam3/model/[io_utils.py](https://github.com/user-attachments/files/23805412/io_utils.py)
sam3/sam3/model/[sam3_tracker_base.py](https://github.com/user-attachments/files/23805413/sam3_tracker_base.py)
sam3/sam3/model/[sam3_video_base.py](https://github.com/user-attachments/files/23805411/sam3_video_base.py)
sam3/sam3/model/[sam3_video_inference.py](https://github.com/user-attachments/files/23805414/sam3_video_inference.py)
sam3/sam3/model/[sam3_video_predictor.py](https://github.com/user-attachments/files/23805415/sam3_video_predictor.py)
sam3/sam3/[model_builder.py](https://github.com/user-attachments/files/23805440/model_builder.py)

What I did:

- Implemented the proposed modification by @ibaiGorordo 
- Loaded the video asynchronously and offloaded it to the CPU ([https://github.com/facebookresearch/sam2/issues/264](https://github.com/facebookresearch/sam3/issues/url) helps reduce CPU RAM usage)
- Loaded SAM3's tracker with `forward_backbone_per_frame_for_eval`, `trim_past_non_cond_mem_for_eval` and `offload_output_to_cpu_for_eval` set to `True` and made them accessible in `build_sam3_video_predictor` arguments (also corrected errors that occur when changing their values)

VRAM is still slowly increasing the more objects you detect, so at some point it will reach an OOM. CPU RAM is used a lot now, so that's not the solution yet.

**Comment by andrewcaunes** [comment]
I have OOM errors occur too, but I'm surprised it's for some specific images, with specific prompts, e.g.:
VideoPredictor prompted with 'car' works well on some 42 images.
Same predictor, with prompt 'road_marking', will OOM on some of those same images.
Are your errors similar ? 

Also, I tried @lborreill  implementation, but still OOM sadly.

**Comment by lborreill** [comment]
> I have OOM errors occur too, but I'm surprised it's for some specific images, with specific prompts, e.g.: VideoPredictor prompted with 'car' works well on some 42 images. Same predictor, with prompt 'road_marking', will OOM on some of those same images. Are your errors similar ?
> 
> Also, I tried [@lborreill](https://github.com/lborreill) implementation, but still OOM sadly.

I suppose there is a lot more road marks than cars in your images. As I said for my implementation, every time a new object is detected, GPU memory still increases a little. But CPU RAM increases a lot faster than GPU memory, the OOM you get is still GPU or CPU now ?

**Comment by andrewcaunes** [comment]
TL;DR: Classes with more instances are more demanding in memory. Use image model if possible for those classes.

Thank you for you response ! My OOMs are only from GPU 
I came to the same realization as what you said : 
"road_marking" just has much more instances than "car", which is very demanding for tracking.
However, I solved my issue by simply handling static classes and dynamic classes separately: 
"car" is handled with the video model, and "road_marking" with the image model, without tracking.

Luckily for me, the dynamic classes that I really need to track are generally less numerous than the static ones, so this works.

**Comment by Aramrt** [comment]
i have problem in the tracking players in basketball after 400 frames i got OOM problem.  They cache everything . forward and backward computation is a lot  I think they do not release frames and etc. it make the SAM3 useless for long videos. By the way we can chunking the video to smaller ones BUT ANY  better idea?

**Comment by ibrahere123** [comment]
U can modify to release the frames after every nth frame it will solve the problem i think.

**Comment by Aramrt** [comment]
@ibrahere123
where should we change ? do you know? i think it is more complicated than it seems. if you know anything about it can we have a meeting or ...?

**Comment by ibrahere123** [comment]
yeah sure mate mail me at 
mibra7528@gmail.com 
we can discuss further
