### ISSUE TITLE
[Bug] SAM3 fails on NVIDIA GB10 (sm_121) with "no kernel image is available for execution on the device"

### ISSUE THREAD

**Issue by laxman-ai** [facebookresearch/sam3#340]
**Description**
On a desktop system with an NVIDIA GB10 GPU (compute capability 12.1, sm_121) and Ubuntu 24.04.3 LTS on arm64, running SAM3 causes a CUDA runtime crash during model initialization. The logs say that the current PyTorch build only supports CUDA capabilities sm_80–sm_90, and then SAM3 fails with CUDA error: no kernel image is available for execution on the device when creating tensors on cuda.

**Environment**
SAM3 version / commit: <commit hash or release tag>

**OS**: Ubuntu 24.04.3 LTS (arm64)

**Kernel**: Linux 6.14.0-1013-nvidia

**GPU:** NVIDIA GB10 (compute capability 12.1 / sm_121)

**Hardware**: Dell Pro Max with GB10

**Python**: 3.10 (Conda env sam3_clean)

**SAM3 install method**: `pip / git clone + pip install -e .`

Steps to Reproduce
Create and activate a clean environment:

bash
`conda create -n sam3_clean python=3.10`
`conda activate sam3_clean`
# Install PyTorch and SAM3 dependencies as in the SAM3 documentation
Run the SAM3‑based script:

bash
python backend/src/run_upload.py( this is a script to upload vectors to weavite db )
The script starts, logs that the feature extractor and SAM3 are initialized on CUDA, and then crashes during model construction.

**Expected Behavior**
SAM3 should either:

Run successfully on NVIDIA GB10 when a compatible GPU build of PyTorch is installed, or

Detect that the GPU architecture (sm_121) is unsupported by the current PyTorch build and fail fast with a clear error or allow explicit CPU fallback.

**Actual Behavior**
At startup, warnings indicate that:

The GPU is NVIDIA GB10 with CUDA capability 12.1.

The installed PyTorch build supports CUDA capabilities only from 8.0 to 9.0.

The GB10 GPU is therefore not compatible with this PyTorch installation.

Later, during SAM3 model construction, the program crashes with:

torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device

The error is raised in PositionEmbeddingSine when calling something like:

**python**
torch.zeros((1, 1) + size, device=dev)
where dev is set to "cuda".

**Additional Context**
Other components (e.g., ResNet feature extractor) log successful initialization on CUDA before the crash, so the GPU is visible but cannot execute kernels with this PyTorch build.

It is unclear whether SAM3 currently supports NVIDIA GB10 / sm_121 on arm64, and if a specific PyTorch + CUDA combination is recommended for this hardware.

Any guidance on:

Supported architectures for SAM3, and

Recommended versions / builds for running on GB10 (arm64),
would be very helpful.

**Comment by IbrahimIrfan** [comment]
Blackwell GPUs require a higher version of PyTorch

This solved it for me on RTX 5090:

```
pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```

This will use CUDA 12.8 instead of 12.6

**Comment by Lk13Antkoo** [comment]
Dear @laxman-ai ,
Can you let me know how much vram needed for segmentation inference only ?
Thank you so much.

**Comment by wulinteousa2-hash** [comment]
Hi @Lk13Antkoo,

For segmentation inference only, I would avoid giving one fixed VRAM number because it depends strongly on image size, model type, and task mode.

For normal 2D images around 1k–2k, it is usually manageable on a modern GPU. For very large microscopy images, such as 50k × 50k, ROI-based inference is safer than full-image inference.

I built a napari plugin for this workflow:
https://github.com/wulinteousa2-hash/napari-sam3-assistant

It supports SAM3 in napari and includes large-image local inference, so SAM runs on smaller ROI windows while preserving the result position in the original image.

Thought this might be useful.
